# docker build -f dockerfile.db -t pgth .
# docker run -p 5433:5432  -e POSTGRES_HOST_AUTH_METHOD=trust -d pgth

FROM postgres:latest
RUN localedef -i th_TH -c -f UTF-8 -A /usr/share/locale/locale.alias th_TH.UTF-8
ENV LANG=th_TH.utf8
COPY init.sql /docker-entrypoint-initdb.d/